spring:

  kafka:
    bootstrap-servers: localhost:9093
    topic-name: task-status-topic
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.example.demo.kafka.TaskDeserializer
      properties:
        fetch-max-wait: 500
        fetch-min-size: 1
        max-poll-records: 50
        max-partition-fetch-bytes: 209715200
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max-request-size: 209715200

  mail:
    protocol: smtp
    host: smtp.mail.ru
    port: 465
    username: test_mail55@mail.ru
    password: JDd4j9nE2Q1eDJn2cB0S
    from: test_mail55@mail.ru
    to: test_mail55@mail.ru
    subject: Task Status Update
    properties:
      smtp:
        auth: true
      starttls:
        enable: true
        require: true

  datasource:
    url: jdbc:postgresql://localhost:54321/my_database
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  logging:
    level:
      org:
        springframework: DEBUG


http:
  logging:
    enabled: true
    level: trace
    log-request-headers: true
    log-response-headers: true
    logRequestBody: true
    logResponseBody: true

server:
  port: 8081